### ISSUE TITLE
Landing pattern playback

### ISSUE THREAD

**Issue by ChrisLane** [ChrisLane/accudrop#35]
### User Story
The user should be able to go to a screen that will allow them to view their landing pattern from a jump. This will be displayed in several different views, one being a top-down view as an overlay on a map, others being views from different sides of the pattern. The user will be able to see what heights they were at from indicators shown on the patterns or by clicking different sections of the pattern.

### Acceptance Criteria
- [x] User is able to see their pattern in bird's eye view
- [ ] User can see what altitude each point in the route was at
- [x] User is able to see their pattern from the side

### Definition of Done
The user is able to view their landing pattern and use it for reflection on how to improve their landing pattern.
